/* eslint-disable @next/next/no-img-element */
import React from "react";
import Head from "next/head";
import * as C from "../components";
import router from "next/router";

export default function Home() {
  const [modalState, setModalState] = React.useState({
    open: false,
  });
  return (
    <>
      <Head>
        <title>🛎️ Qr Code Concierge</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-screen items-center justify-center bg-indigo-50 px-4">
          <div className="max-w-sm overflow-hidden rounded-xl bg-white shadow-md duration-200 hover:scale-105 hover:shadow-xl">
            <img
              src="https://cdn.discordapp.com/attachments/1082297301072105544/1084972423193051176/467ab9e0644c9c89c99b7ed569337c25.png"
              alt="plant"
              className="h-auto w-full"
            />
            <div className="p-5">
              <p className="text-medium mb-5 text-gray-700">
                - Hi, sir, do you have a qr-code ?
              </p>
              <C.DefaultButton
                onClick={() => router.push("/as")}
                text="Yes, I have"
              />
              <C.DefaultButton
                text="Not yet..."
                onClick={() =>
                  setModalState({
                    open: true,
                  })
                }
              />
            </div>
          </div>
        </div>
        <C.CreateModal
          info={modalState}
          closeModal={() =>
            setModalState({
              open: false,
            })
          }
        />
      </main>
    </>
  );
}
